### ISSUE TITLE
LICENCE file

### ISSUE THREAD

**Issue by Unifex** [saket-shetty/Post-it#1]
Looking at this on a mobile device so I may be missing it. Just wondering what licence this is released under.

I have a project I'll be releasing under an open source licence and this would be an awesome addition to it.

**Comment by saket-shetty** [comment]
Hello Sir, sorry for the late response you have all write to use it however you want

**Comment by saket-shetty** [comment]
> Looking at this on a mobile device so I may be missing it. Just wondering what licence this is released under.
> 
> I have a project I'll be releasing under an open source licence and this would be an awesome addition to it.

Hello Sir, sorry for the late response you have all write to use it however you want

**Comment by saket-shetty** [comment]
@Unifex Hello Sir, sorry for the late response. Yes you can use my app in your new project I have no issue.

**Comment by shaadart** [comment]
Thanks @saket-shetty I will Really contibute on it. and Improve it.
