### ISSUE TITLE
Need more information on Firebase Database Setting

### ISSUE THREAD

**Issue by ksy5662** [saket-shetty/Post-it#3]

**Comment by saket-shetty** [comment]
> Dear saket-shetty,
> 
> Need more information on Firebase Database Setting.
> 
> Thanks,
> 
> Jay



> Dear saket-shetty,
> 
> Need more information on Firebase Database Setting.
> 
> Thanks,
> 
> Jay

@ksy5662 do you know how issues work dude. what do mean by more info on firebase its a database to store data, stop oppening 1000s of issue on my repo
