### ISSUE TITLE
keystore file missing!

### ISSUE THREAD

**Issue by alholan** [saket-shetty/Post-it#5]
on mac. flutter and running on VS Code editor..
 **key.properties file contect:**
> storePassword=android
> keyPassword=android
> keyAlias=upload

storeFile=**C:/Users/Admin/upload-keystore.jks**. (_not included_)
how can we generate keyStore file for the post-it project?

**Comment by saket-shetty** [comment]
Hello, please go through the documentation of flutter regarding the creation of Signed apk they have explained the steps to create the .jks file.
